# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# ===================================================================

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basedb?useSSL=false
    username: root
    password: 12345678

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:/db/migration

# ===================================================================
# Logger
# ===================================================================

logging:
  level:
    root: INFO